"""initial migration

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码(如000001.SZ)'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码(如000001)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('area', sa.String(length=100), nullable=True, comment='地域'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='所属行业'),
    sa.Column('list_date', sa.String(length=10), nullable=True, comment='上市日期'),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('daily_hq',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True, comment='开盘价'),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True, comment='最高价'),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True, comment='最低价'),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True, comment='收盘价'),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=4), nullable=True, comment='昨收价'),
    sa.Column('change', sa.Numeric(precision=12, scale=4), nullable=True, comment='涨跌额'),
    sa.Column('pct_chg', sa.Numeric(precision=12, scale=4), nullable=True, comment='涨跌幅(百分比)'),
    sa.Column('vol', sa.Numeric(precision=18, scale=4), nullable=True, comment='成交量(手)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True, comment='成交额(千元)'),
    sa.ForeignKeyConstraint(['ts_code'], ['stocks.ts_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_hq_pct_chg', 'daily_hq', ['pct_chg'], unique=False)
    op.create_index('idx_daily_hq_trade_date', 'daily_hq', ['trade_date'], unique=False)
    op.create_index('idx_daily_hq_ts_code', 'daily_hq', ['ts_code'], unique=False)
    op.create_index('idx_daily_hq_ts_trade', 'daily_hq', ['ts_code', 'trade_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_daily_hq_ts_trade', table_name='daily_hq')
    op.drop_index('idx_daily_hq_ts_code', table_name='daily_hq')
    op.drop_index('idx_daily_hq_trade_date', table_name='daily_hq')
    op.drop_index('idx_daily_hq_pct_chg', table_name='daily_hq')
    op.drop_table('daily_hq')
    op.drop_table('stocks')
    # ### end Alembic commands ###
