"""add_bak_daily_table

Revision ID: 0988749dba40
Revises: bccf57168606
Create Date: 2026-03-14 17:40:07.579598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0988749dba40'
down_revision: Union[str, None] = 'bccf57168606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bak_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('selling', sa.Numeric(precision=18, scale=4), nullable=True, comment='内盘(主动卖, 手)'),
    sa.Column('buying', sa.Numeric(precision=18, scale=4), nullable=True, comment='外盘(主动买, 手)'),
    sa.ForeignKeyConstraint(['ts_code'], ['stocks.ts_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bak_daily_trade_date', 'bak_daily', ['trade_date'], unique=False)
    op.create_index('idx_bak_daily_ts_code', 'bak_daily', ['ts_code'], unique=False)
    op.create_index('idx_bak_daily_ts_trade', 'bak_daily', ['ts_code', 'trade_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bak_daily_ts_trade', table_name='bak_daily')
    op.drop_index('idx_bak_daily_ts_code', table_name='bak_daily')
    op.drop_index('idx_bak_daily_trade_date', table_name='bak_daily')
    op.drop_table('bak_daily')
    # ### end Alembic commands ###
