"""add_user_favorites_table

Revision ID: bccf57168606
Revises: 005
Create Date: 2026-02-25 21:10:58.458994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccf57168606'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('ts_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='添加时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_favorites_ts_code', 'user_favorites', ['ts_code'], unique=False)
    op.create_index('idx_user_favorites_user_id', 'user_favorites', ['user_id'], unique=False)
    op.create_index('idx_user_favorites_user_ts', 'user_favorites', ['user_id', 'ts_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_favorites_user_ts', table_name='user_favorites')
    op.drop_index('idx_user_favorites_user_id', table_name='user_favorites')
    op.drop_index('idx_user_favorites_ts_code', table_name='user_favorites')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
